---
- hosts: controller
  connection: local
  gather_facts: false
  vars:
    assign_galaxy_credentials_to_org: false
  module_defaults:
    group/awx.awx.controller:
      controller_host: "{{ vault_controller_hostname }}"
      controller_username: "{{ vault_controller_username }}"
      controller_password: "{{ vault_controller_password }}"
      validate_certs: "{{ vault_controller_validate_certs }}"
  tasks:
    - name: "Deploy the organizations"
      awx.awx.organization:
        name: "{{ organization_item.name }}"
        description: "{{ organization_item.description }}"
      loop: "{{ controller_organizations }}"
      loop_control:
        loop_var: organization_item
      tags:
        - organizations

    - name: "Deploy the credentials"
      awx.awx.credential: "{{ credential_item }}"
      loop: "{{ controller_credentials }}"
      loop_control:
        loop_var: credential_item
      tags:
        - credentials

    - name: "Add galaxy credentials to organizations"
      awx.awx.organization: "{{ organization_item }}"
      loop: "{{ controller_organizations }}"
      loop_control:
        loop_var: organization_item
      tags:
        - organizations
        - credentials

    - name: "Deploy the projects"
      awx.awx.project: "{{ project_item }}"
      loop: "{{ controller_projects }}"
      loop_control:
        loop_var: project_item
      tags:
        - projects

    - name: "Deploy the instance groups"
      awx.awx.instance_group: "{{ instance_group_item }}"
      loop: "{{ controller_instance_groups }}"
      loop_control:
        loop_var: instance_group_item
      tags:
        - instance_groups

    - name: "Deploy the inventories"
      awx.awx.inventory: "{{ inventory_item }}"
      loop: "{{ controller_inventories }}"
      loop_control:
        loop_var: inventory_item
      tags:
        - inventories

    - name: "Deploy the hosts"
      awx.awx.host: "{{ host_item }}"
      loop: "{{ controller_hosts }}"
      loop_control:
        loop_var: host_item
      tags:
        - hosts

    - name: "Deploy the groups"
      awx.awx.group: "{{ group_item }}"
      loop: "{{ controller_groups }}"
      loop_control:
        loop_var: group_item
      tags:
        - groups

    - name: "Deploy the execution environments"
      awx.awx.execution_environment: "{{ execution_environments_item }}"
      loop: "{{ controller_execution_environments }}"
      loop_control:
        loop_var: execution_environments_item
      tags: execution_environments

    - name: "Deploy the job templates"
      awx.awx.job_template: "{{ job_template_item }}"
      loop: "{{ controller_templates }}"
      loop_control:
        loop_var: job_template_item
      tags:
        - job_templates

    - name: "Deploy the workflows"
      awx.awx.workflow_job_template: "{{ workflow_item }}"
      loop: "{{ controller_workflows }}"
      loop_control:
        loop_var: workflow_item
      tags:
        - workflow_job_templates

    - name: "Deploy the workflow nodes"
      awx.awx.workflow_job_template_node: "{{ node_item }}"
      loop: "{{ controller_workflow_nodes }}"
      loop_control:
        loop_var: node_item
      tags:
        - workflow_job_templates
...
