---
- hosts: controller
  connection: local
  gather_facts: false
  vars_files:
    - controller_organizations.yaml
    - controller_credentials.yaml
    - controller_projects.yaml
    - controller_inventories.yaml
    - controller_instance_groups.yaml
    - controller_hosts.yaml
    - controller_templates.yaml
    - controller_workflows.yaml
  module_defaults:
    ansible.controller.organization: &common
      controller_host: "{{ vault_controller_hostname }}"
      controller_username: "{{ vault_controller_username }}"
      controller_password: "{{ vault_controller_password }}"
      validate_certs: "{{ vault_controller_validate_certs }}"
    ansible.controller.credential: *common
    ansible.controller.project: *common
    ansible.controller.inventory: *common
    ansible.controller.instance_group: *common
    ansible.controller.host: *common
    ansible.controller.job_template: *common
    ansible.controller.workflow_job_template: *common
  tasks:
    - name: "Deploy the organizations"
      ansible.controller.organization: "{{ organization_item }}"
      loop: "{{ controller_organizations }}"
      loop_control:
        loop_var: organization_item

    - name: "Deploy the credentials"
      ansible.controller.credential: "{{ credential_item }}"
      loop: "{{ controller_credentials }}"
      loop_control:
        loop_var: credential_item

    - name: "Deploy the projects"
      ansible.controller.project: "{{ project_item }}"
      loop: "{{ controller_projects }}"
      loop_control:
        loop_var: project_item

    - name: "Deploy the inventories"
      ansible.controller.inventory: "{{ inventory_item }}"
      loop: "{{ controller_inventories }}"
      loop_control:
        loop_var: inventory_item

    - name: "Deploy the instance groups"
      ansible.controller.instance_group: "{{ instance_group_item }}"
      loop: "{{ controller_instance_groups }}"
      loop_control:
        loop_var: instance_group_item

    - name: "Deploy the hosts"
      ansible.controller.host: "{{ host_item }}"
      loop: "{{ controller_hosts }}"
      loop_control:
        loop_var: host_item

    - name: "Deploy the job templates"
      ansible.controller.job_template: "{{ job_template_item }}"
      loop: "{{ controller_templates }}"
      loop_control:
        loop_var: job_template_item

    - name: "Deploy the workflows"
      ansible.controller.workflow_job_template: "{{ workflow_item }}"
      loop: "{{ controller_workflows }}"
      loop_control:
        loop_var: workflow_item
...
