---
- hosts: "{{ k8s_flavor }}"
  connection: local
  gather_facts: false
  tasks:
    - name: Get Cluster information
      kubernetes.core.k8s_cluster_info:
        api_key: "{{ bearer_token }}"
        host: "{{ host }}"
        validate_certs: "{{ verify_ssl }}"
      register: api_status

    - name: Show k8s version
      debug:
        msg: "{{ api_status.version.server }}"


