---
- hosts: "{{ k8s_flavor | default ('all') }}"
  connection: local
  gather_facts: true
  module_defaults:
    group/k8s:
      api_key: "{{ bearer_token }}"
      host: "{{ host }}"
      validate_certs: "{{ ssl_ca_cert }}"
  tasks:
    - debug:
        msg:
          - "Bearer: {{ bearer_token }}"
          - "{{ lookup('ansible.builtin.pipe', 'env') }}"
          - "{{ vars }}"

    - name: Get Cluster information
      kubernetes.core.k8s_cluster_info:
        api_key: "{{ bearer_token | default(lookup('env','K8S_AUTH_API_KEY'), true) }}"
        host: "{{ host | default(lookup('env','K8S_AUTH_HOST'), true) }}"
        validate_certs: "{{ verify_ssl | default(lookup('env','K8S_AUTH_VERIFY_SSL'), true) }}"
      register: api_status
      vars:
        is_kubernetes: "{{ lookup('pipe', 'env | grep KUBERNETES_ | wc -l') | int }}"
      when: is_kubernetes > 0

    - name: Show k8s version
      debug:
        msg:
          - "API Version: {{ api_status.version.server | default('not in Kubernetes') }}"
          - "{{ k8s_flavor }}"
          - "is_kubernetes: {{ lookup('pipe', 'env | grep KUBERNETES_ | wc -l') }}"
          - "hostname: {{ ansible_facts.hostname }}"
...
