---
- hosts: "{{ k8s_flavor }}"
  connection: local
  gather_facts: false
  module_defaults:
    group/k8s:
      api_key: "{{ bearer_token }}"
      host: "{{ host }}"
      validate_certs: "{{ ssl_ca_cert }}"
  tasks:
    - debug:
        msg:
          - "Bearer: {{ bearer_token }}"
          - "{{ lookup('ansible.builtin.pipe', 'env') }}"

    - name: Get Cluster information
      kubernetes.core.k8s_cluster_info:
        api_key: "{{ bearer_token | default(lookup('env','K8S_AUTH_API_KEY'), true) }}"
        host: "{{ host | default(lookup('env','K8S_AUTH_HOST'), true) }}"
        validate_certs: "{{ verify_ssl | default(lookup('env','K8S_AUTH_VERIFY_SSL'), true) }}"
      register: api_status

    - name: Show k8s version
      debug:
        msg:
          - "{{ api_status.version.server }}"
          - "{{ k8s_flavor }}"
...
