---
- hosts: "{{ k8s_flavor }}"
  connection: local
  gather_facts: false
  tasks:
    - debug:
        msg:
          - "{{ lookup('ansible.builtin.pipe', 'env') }}"

    - name: Get Cluster information
      kubernetes.core.k8s_cluster_info:
        api_key: "{{ bearer_token | default(lookup('env','K8S_AUTH_API_KEY')) }}"
        host: "{{ host | default(lookup('env','K8S_AUTH_HOST')) }}"
        validate_certs: "{{ verify_ssl | default(lookup('env','K8S_AUTH_VERIFY_SSL')) }}"
      register: api_status

    - name: Show k8s version
      debug:
        msg:
          - "{{ api_status.version.server }}"
          - "{{  }}"


