---
controller_workflow_nodes:
  - identifier: "K8S_AWS"
    workflow_job_template: "{{ orgs }} Demo Workflow"
    unified_job_template: "{{ orgs }} Demo Job Template"
    inventory: "{{ orgs }} Demo Inventory AWS"
    credentials: "{{ orgs }} Demo Credential OCP AWS"
  - identifier: "K8S_AZU"
    workflow_job_template: "{{ orgs }} Demo Workflow"
    unified_job_template: "{{ orgs }} Demo Job Template"
    inventory: "{{ orgs }} Demo Inventory AZU"
    credentials: "{{ orgs }} Demo Credential OCP AZU"
  - identifier: "VM_ON_PREM"
    workflow_job_template: "{{ orgs }} Demo Workflow"
    unified_job_template: "{{ orgs }} Demo Job Template"
    inventory: "{{ orgs }} Demo Inventory VM_ON_PREM"
    credentials: []
...
