---
controller_inventories:
  - name: "{{ orgs }} Demo Inventory AWS"
    description: "Demo Inventory AWS"
    organization: "{{ orgs }}"
    instance_groups:
      - AWS

  - name: "{{ orgs }} Demo Inventory AZU"
    description: "Demo Inventory AZU"
    organization: "{{ orgs }}"
    instance_groups:
      - AZU
...
