---
controller_workflows:
  - name: "{{ orgs }} Demo Workflow"
    state: present
    description: "Demo Workflow"
    ask_variables_on_launch: true
    allow_simultaneous: true
    organization: "{{ orgs }}"
    survey_enabled: false
    survey_spec: {}
...
