---
controller_templates:
  - name: "{{ orgs }} Demo Job Template"
    description: "Demo Job Template"
    organization: "{{ orgs }}"
    project: "{{ orgs }} Demo Project"
    playbook: "get_k8s_cluster_info.yaml"
    job_type: run
    fact_caching_enabled: false
    concurrent_jobs_enabled: true
    ask_credential_on_launch: true
    ask_inventory_on_launch: true
    extra_vars:
      ansible_python_interpreter: /usr/bin/python3
      ansible_async_dir: /home/runner/.ansible_async/
    execution_environment: "ee-k8s"
...
