---
controller_workflows:
  - name: "{{ orgs }} Demo Workflow"
    state: present
    description: "Demo Workflow"
    ask_variables_on_launch: true
    allow_simultaneous: true
    organization: "{{ orgs }}"
    survey_enabled: false
    survey_spec: {}
    scheme:
      - identifier: "LAUNCH_CI_{{ orgs }}_OCP"
        unified_job_template:
          organization:
            name: "{{ orgs }}"
          name: "{{ orgs }} Demo Job Template"
          type: job_template
        inventory: "{{ orgs }} Demo Inventory OCP"
        credentials:
          - name: "{{ orgs }} Demo Credential OCP"
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
          credentials: []
      - identifier: "LAUNCH_CI_{{ orgs }}_EKS"
        unified_job_template:
          organization:
            name: "{{ orgs }}"
          name: "{{ orgs }} Demo Job Template"
          type: job_template
        inventory: "{{ orgs }} Demo Inventory EKS"
        credentials:
          - name: "{{ orgs }} Demo Credential EKS"
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
          credentials: []
...
