---
controller_hosts:
  - name: aws-instance-group
    description: localhost
    inventory: "{{ orgs }} Demo Inventory AWS"

  - name: azu-instance-group
    description: localhost
    inventory: "{{ orgs }} Demo Inventory AZU"

  - name: vm-onprem-instance-group
    description: localhost
    inventory: "{{ orgs }} Demo Inventory VM_ON_PREM"
...
